#---------------------------
# CONIFIG FOR ADMIN SECTION
#---------------------------

backend:
  name: github
  repo: ricjhill/mjanecek
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: content/posts
    create: true
    slug: '{{slug}}'
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Body
        name: body
        widget: markdown
  - name: news
    label: News
    folder: content/news
    create: true
    slug: '{{slug}}'
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Body
        name: body
        widget: markdown
